<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
   
        $this->changeColumn('creation', 'mini_desc1', 'clob', '', array(
             ));
        $this->changeColumn('creation', 'mini_desc2', 'clob', '', array(
             ));
    }

    public function down()
    {
        
    }
}