<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('creation', 'code', 'varchar', '20', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}