<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('techno', 'url', 'varchar', '255', array(
             'notnull' => '',
             ));
	}
    public function down()
    {
        $this->removeColumn('techno', 'url');
    }
}