<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('article', 'publie', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->addColumn('article', 'afficher_chapeau', 'boolean', '25', array(
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('article', 'publie');
        $this->removeColumn('article', 'afficher_chapeau');
    }
}