<?php

/**
 * Article
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    foliov4
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Article extends BaseArticle
{ 

  private $article_suivant = null;
  private $article_precedent = null;
  
  public function __toString()
  {
    return $this->getTitre();
  }
  
  public function getNbCommentairesS()
  {
    $nb = $this->getNbCommentaires();
    if ($nb==0) return "Aucun commentaire";
    elseif ($nb==1) return "1 commentaire";
    else return $nb." commentaires";
  }
  
  public function getNbCommentaires()
  {
    return  CommentaireTable::getInstance()->createQuery('c')->where('article_id = ?', $this->getId())->count();
  }
  
  public function incrementerLus()
  {
    $this->setNbLu($this->getNbLu()+1);
  }
  
  public function getCategorieSlug()
  {
    // Optimizable
    return $this->getCategorie()->getSlug();
  }
  
  public function getArticleSuivant()
  {
    if ($this->article_suivant === null)
    {
      $this->article_suivant = ArticleTable::getInstance()->createQuery('a')
        ->where('a.date > ?', $this->getDate())
        ->orderBy('a.date ASC')
        ->limit(1)
        ->fetchOne();
    }
    return $this->article_suivant;
  }
  
  public function getArticlePrecedent()
  {
    if ($this->article_precedent === null)
    {
      $this->article_precedent = ArticleTable::getInstance()->createQuery('a')
        ->where('a.date < ?', $this->getDate())
        ->orderBy('a.date DESC')
        ->limit(1)
        ->fetchOne();
    }
    return $this->article_precedent;
  }  
  
  public function hasArticleSuivant()
  {
    return $this->getArticleSuivant()!==false;
  }

  public function hasArticlePrecedent()
  {
    return $this->getArticlePrecedent()!==false;
  }
 
}