<?php

/**
 * Techno
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    foliov4
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Techno extends BaseTechno
{
  
  public function __toString()
  {
    return $this->getNom();
  }
  
  public function getLogo()
  {
    if (Toolbox::isRawDump()) return $this->_get('logo');
     
    $logo = $this->_get('logo');
    $base = '/uploads/techno/';
    
    if (empty($logo)) return null;
    
    return $base.$logo;
  }
  
}