<?php

/**
 * BaseCategorie
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $titre
 * @property clob $description
 * @property varchar $logo
 * @property Doctrine_Collection $Articles
 * 
 * @method varchar             getTitre()       Returns the current record's "titre" value
 * @method clob                getDescription() Returns the current record's "description" value
 * @method varchar             getLogo()        Returns the current record's "logo" value
 * @method Doctrine_Collection getArticles()    Returns the current record's "Articles" collection
 * @method Categorie           setTitre()       Sets the current record's "titre" value
 * @method Categorie           setDescription() Sets the current record's "description" value
 * @method Categorie           setLogo()        Sets the current record's "logo" value
 * @method Categorie           setArticles()    Sets the current record's "Articles" collection
 * 
 * @package    foliov4
 * @subpackage model
 * @author     Julien Lafont
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategorie extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('categorie');
        $this->hasColumn('titre', 'varchar', 200, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('logo', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Article as Articles', array(
             'local' => 'id',
             'foreign' => 'categorie_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'titre',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($sluggable0);
    }
}