<?php

/**
 * BaseArticlesLies
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $article_src_id
 * @property integer $article_liee_id
 * @property Article $ArticleSrc
 * @property Article $ArticleLie
 * 
 * @method integer      getArticleSrcId()    Returns the current record's "article_src_id" value
 * @method integer      getArticleLieeId()   Returns the current record's "article_liee_id" value
 * @method Article      getArticleSrc()      Returns the current record's "ArticleSrc" value
 * @method Article      getArticleLie()      Returns the current record's "ArticleLie" value
 * @method ArticlesLies setArticleSrcId()    Sets the current record's "article_src_id" value
 * @method ArticlesLies setArticleLieeId()   Sets the current record's "article_liee_id" value
 * @method ArticlesLies setArticleSrc()      Sets the current record's "ArticleSrc" value
 * @method ArticlesLies setArticleLie()      Sets the current record's "ArticleLie" value
 * 
 * @package    foliov4
 * @subpackage model
 * @author     Julien Lafont
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticlesLies extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('articles_lies');
        $this->hasColumn('article_src_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('article_liee_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Article as ArticleSrc', array(
             'local' => 'article_src_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Article as ArticleLie', array(
             'local' => 'article_liee_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}