<?php

/**
 * BaseCategorieFolio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $titre
 * @property Doctrine_Collection $Creations
 * 
 * @method varchar             getTitre()     Returns the current record's "titre" value
 * @method Doctrine_Collection getCreations() Returns the current record's "Creations" collection
 * @method CategorieFolio      setTitre()     Sets the current record's "titre" value
 * @method CategorieFolio      setCreations() Sets the current record's "Creations" collection
 * 
 * @package    foliov4
 * @subpackage model
 * @author     Julien Lafont
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategorieFolio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('categorie_folio');
        $this->hasColumn('titre', 'varchar', 200, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Creation as Creations', array(
             'local' => 'id',
             'foreign' => 'categorie_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'titre',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($sluggable0);
    }
}